### ISSUE TITLE
Only build on package releases

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/epiforecasts.r-universe.dev#7]
Current the universe and GitHub have overlapping feature sets. We could change this by making the universe only build on package releases. This would be nice as it would offer a versioned/controlled release process for those packages not on CRAN and for those packages that are enable small universe only releases vs larger CRAN releases.

See: https://github.com/epinowcast/universe/blob/b5fea16e82e308f60c9a3f47f86fe49fbc114253/packages.json#L5

**Comment by Bisaloo** [comment]
@sbfnk @nikosbosse, as other maintainers of epiforecasts packages, any thoughts on this? If so, I can make the switch later next week.

**Comment by Bisaloo** [comment]
One potential downside I see is that we would have to be sure we always remember to tag a release on GitHub, which can be easy to forget.

**Comment by seabbs** [comment]
Yes that is very true, good point.

**Comment by seabbs** [comment]
Bumping this. @sbfnk what do you think. I really don't want `main` being built on Universe as then can use it for stable installs.

**Comment by Bisaloo** [comment]
Random thought: it would be possible to have two different settings on two different r-universe. One could always build from latest `main` and the other only from releases.

Or would this be too confusing? :thinking:

**Comment by seabbs** [comment]
that is a fun idea - I like it. Seems like maybe a feature that needs to be added to R-Universe itself though perhaps?

**Comment by seabbs** [comment]
Now I look at this again I think we can do it per package so perhaps I will just change `EpiNow2`? That could also get confusing though

**Comment by Bisaloo** [comment]
> Seems like maybe a feature that needs to be added to R-Universe itself though perhaps?

I mean:

- epiforecasts.r-universe.dev would provide builds on releases
- seabbs.r-universe.dev would provide builds on each commit on `main`

Or the other way around.

As I said, I'm still not convinced it's a good idea myself but sharing just in case.

**Comment by seabbs** [comment]
yes I understand what you mean. I meant that this seems like a nice feature for a single universe to have (i.e access to both stable releases and the latest committed code). Essentially i am suggesting it could be opened as an issue over there and discussed there vs us hacking anything together. 

I don't have developer bandwidth to maintain multiple universes for epiforecasts packages.
